apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-app-deployment
  namespace: gke-ai-namespace 
  labels:
    app: gradio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-app
  template:
    metadata:
      labels:
        app: gradio-app
    spec:
      containers:
        - name: gradio-app-container
          image: {{REGION}}-docker.pkg.dev/{{PROJECT_ID}}/{{ARTIFACT_REGISTRY}}/{{model_image}}-gradio-app:latest
          ports:
            - containerPort: 7860
          env:
            - name: LLM_SERVICE_URL
              value: "http://llm-service.gke-ai-namespace.svc.cluster.local"