apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: gke-ai-namespace  
spec:
  selector:
    app: llm
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
