apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
  namespace: gke-ai-namespace  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      serviceAccountName: gpu-k8s-sa
      containers:
      - name: llm
        image: {{REGION}}-docker.pkg.dev/{{PROJECT_ID}}/{{ARTIFACT_REGISTRY}}/{{model_image}}-cpu-inference:latest
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "8"
            memory: "32Gi"
        env:
        - name: MODEL_DIR
          value: "/app/model_weights"
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/app/model_weights"
          name: gcsfuse-volume
      volumes:
      - name: gcsfuse-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: {{bucket_name}}
            mountOptions: "implicit-dirs"
