apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: gke-ai-namespace    
  labels:
    app: llm
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: llm