apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
  namespace: gke-ai-namespace  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
      annotations:
        gke-gcsfuse/volumes: "true"  # Important annotation
    spec:
      serviceAccountName: gpu-k8s-sa
      # Main application container
      containers:
      - name: llm
        image: {{REGION}}-docker.pkg.dev/{{PROJECT_ID}}/{{ARTIFACT_REGISTRY}}/{{model_image}}-cpu-inference:latest
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
        env:
        - name: MODEL_DIR
          value: "/app/{{folder_name}}"
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/app/{{folder_name}}"
          name: gcsfuse-volume
          readOnly: false
      # GCSFuse sidecar container (must be named 'gcsfuse')
      - name: gcsfuse
        image: gcr.io/cloud-solutions-images/gcsfuse-csi:v1.0.2
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command: ["/bin/sleep"]
        args: ["infinity"]
        volumeMounts:
        - mountPath: "/gcsfuse-tmp"
          name: gcsfuse-tmp
      volumes:
      - name: gcsfuse-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: {{bucket_name}}
            mountOptions: "implicit-dirs,uid=1000,gid=1000"  # Added UID/GID
      - name: gcsfuse-tmp
        emptyDir: {}