apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcsfuse-pvc
  namespace: gke-ai-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard-rwo"
