name: Deploy Gradio Image (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"

      - name: Enable Required Services
        run: |
          gcloud services enable container.googleapis.com artifactregistry.googleapis.com

      - name: Configure Docker to Authenticate with Google Artifact Registry
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Set Working Directory
        run: |
          cd TinyLlama-1.1B-Chat-v1.0/LLM-Gradio-App

      - name: Create and Push Docker Image
        run: |
          export PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          export ARTIFACT_REGISTRY=${{ secrets.GCP_ARTIFACT_REGISTRY }}
          export REGION=${{ secrets.GCP_REGION }}

          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/gradio-app:latest .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/gradio-app:latest

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials llm-deploy --region us-east4 --project ${{ secrets.PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True

      - name: Create Kubernetes Secret for Hugging Face Token
        run: |
          kubectl create secret generic hf-secret \
            --from-literal=HUGGING_FACE_TOKEN=${{ secrets.HUGGING_FACE_TOKEN }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Image to GKE
        run: |
          cd TinyLlama-1.1B-Chat-v1.0/LLM-Gradio-App
          kubectl apply -f gradio-deployment.yaml

      - name: Wait for External IP
        run: |
          echo "Waiting for External IP..."
          for i in {1..10}; do
            EXTERNAL_IP=$(kubectl get svc gradio-service -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [[ -n "$EXTERNAL_IP" ]]; then
              echo "External IP assigned: $EXTERNAL_IP"
              echo "Access the Gradio app at: http://$EXTERNAL_IP"
              exit 0
            fi
            echo "External IP not assigned yet. Retrying in 30 seconds..."
            sleep 30
          done
          echo "ERROR: Timed out waiting for External IP."
          exit 1