name: Deploy Model Image (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          project_id: "genai-model-dev-deploy"
          workload_identity_provider: "projects/630538663455/locations/global/workloadIdentityPools/github/providers/llm-kubernetes-deployment"
          service_account: "llm-model-serving-2025@genai-model-dev-deploy.iam.gserviceaccount.com"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "genai-model-dev-deploy"

      - name: Enable Required Services
        run: |
          gcloud services enable container.googleapis.com

      - name: Create and Push Docker Image
        run: |
          #!/bin/bash
          docker build -t us-east4-docker.pkg.dev/genai-model-dev-deploy/gen-ai-app-registry/tinyllama-cpu-inference:latest .
          docker push us-east4-docker.pkg.dev/genai-model-dev-deploy/gen-ai-app-registry/tinyllama-cpu-inference:latest

      - name: Deploy image
        run: |
          kubectl apply -f llm-deployment.yaml

