name: Deploy GKE Cluster (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"

      - name: Enable Required Services
        run: |
          gcloud services enable container.googleapis.com

      - name: Create GKE Cluster
        run: |
          #!/bin/bash
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

          gcloud container clusters create llm-deploy --location ${{ secrets.GCP_REGION }} \
            --workload-pool ${{ secrets.GCP_PROJECT_ID }}.svc.id.goog \
            --enable-image-streaming --node-locations=${{ secrets.GCP_REGION }} \
            --machine-type n2d-standard-4 --num-nodes 1 \
            --release-channel=rapid

          # Get cluster credentials
          gcloud container clusters get-credentials llm-deploy --region=$${{ secrets.GCP_REGION }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True

